# Generated by Django 5.2.4 on 2025-07-31 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='is_multiple_choice',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_text',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuizContent',
        ),
    ]
