# Generated by Django 5.2.4 on 2025-07-31 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quizquestion_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
