# Generated by Django 5.2.4 on 2025-07-31 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileContent',
        ),
        migrations.DeleteModel(
            name='LabContent',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lessonitem',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonItem',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizContent',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
