# Generated by Django 5.2.4 on 2025-07-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_user_course_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='banner',
            field=models.ImageField(null=True, upload_to='banners/'),
        ),
    ]
