# Generated by Django 5.2.4 on 2025-07-31 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_thumbnail_remove_course_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.module'),
        ),
    ]
